### ISSUE TITLE
Implement search filtering for posts

### ISSUE THREAD

**Issue by aPruner** [crisisboard/opencrisisboard#12]
Frontend search functionality would be great so that users can filter posts for certain keywords.

The implementation details are yet to be fully determined, but this will certainly involve building a stateful search bar component and functionality to filter the posts (via a substring search or some similar algorithm) based on the string entered into the search bar component.

TODO here: 
- UX design mockup for search component
- Build search component
- Build substring search filter functionality
- Unit testing for search component

**Comment by aaoyekanmi4** [comment]
I can work on this

**Comment by aPruner** [comment]
Thanks for taking and finishing this one @aaoyekanmi4 ! We appreciate your contribution! :) 

Closing as this was implemented in #30
