### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by rfink** [crisisboard/opencrisisboard#5]
Saw this posted on helpwithcovid.com and signed up to volunteer for the project. How can I assist?

**Comment by findwaterio** [comment]
same here

**Comment by adbci** [comment]
Same here

**Comment by aPruner** [comment]
Hi everyone!

Thanks for checking out the project. Please refer to the `CONTRIBUTING.md` file in the root project directory for more information on contributing. We've just opened our issues tab so we haven't fleshed out issues for all of the features we're looking to implement yet (and we also haven't yet created bug reports for our bugs), so please keep your eyes peeled for bugs and features that we need help with.
