### ISSUE TITLE
Why not just use Discourse?

### ISSUE THREAD

**Issue by maxgiraldo** [crisisboard/opencrisisboard#6]
It's FOSS and you don't have to develop anything: https://www.discourse.org/

**Comment by PimDeWitte** [comment]
Thank you for the feedback - great idea. We are going to move forward with this due to the simplicity of deployment. If any of the discourse developers want to merge in features, we would love that

**Comment by PimDeWitte** [comment]
PS: In parallel, chatting with them to see if we can make deploys easier
