### ISSUE TITLE
Your website is down

### ISSUE THREAD

**Issue by jesselve** [crisisboard/opencrisisboard#7]
As of now (2020-03-20 14:41:00 UTC)

See https://www.websiteplanet.com/webtools/down-or-not/?DorN=https://opencrisisboard.org/

![image](https://user-images.githubusercontent.com/3021609/77174331-43e66500-6a97-11ea-89c5-9dc819944973.png)

Do you need help with Dev Ops or better hosting?

**Comment by PimDeWitte** [comment]
Fixed - switched hosts.
